// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAApYADBQTuKahEUKy6wGO7ahgO4n_gZgQ',
    appId: '1:798448726161:web:3bc1071a080ab0e5c08f30',
    messagingSenderId: '798448726161',
    projectId: 'projectopdm-8b5df',
    authDomain: 'projectopdm-8b5df.firebaseapp.com',
    storageBucket: 'projectopdm-8b5df.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACkXMUMqtXpLrVAiT5nQu1Ne9ttfJTowY',
    appId: '1:798448726161:android:8dcf802bef6e85cac08f30',
    messagingSenderId: '798448726161',
    projectId: 'projectopdm-8b5df',
    storageBucket: 'projectopdm-8b5df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYPiZ-9eihyEzP9HYh_lmbfMx2cqDGftk',
    appId: '1:798448726161:ios:280eab6379920973c08f30',
    messagingSenderId: '798448726161',
    projectId: 'projectopdm-8b5df',
    storageBucket: 'projectopdm-8b5df.firebasestorage.app',
    iosBundleId: 'com.pdm.selfhealthcontrol',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYPiZ-9eihyEzP9HYh_lmbfMx2cqDGftk',
    appId: '1:798448726161:ios:280eab6379920973c08f30',
    messagingSenderId: '798448726161',
    projectId: 'projectopdm-8b5df',
    storageBucket: 'projectopdm-8b5df.firebasestorage.app',
    iosBundleId: 'com.pdm.selfhealthcontrol',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAApYADBQTuKahEUKy6wGO7ahgO4n_gZgQ',
    appId: '1:798448726161:web:f64e760d3f4c334cc08f30',
    messagingSenderId: '798448726161',
    projectId: 'projectopdm-8b5df',
    authDomain: 'projectopdm-8b5df.firebaseapp.com',
    storageBucket: 'projectopdm-8b5df.firebasestorage.app',
  );
}
